Repository StUdY-TrEk/Boot-Camping, pull requests merged in 2024-07, with the labels that each got.

#3 [2024/07/24] feat/auth 공통 구현 : 로그인/회원가입 프론트 연동
  src/main/resources/application.properties
  src/main/resources/static/css/login.css
  src/main/resources/static/js/login.js
  src/main/resources/templates/login.html
Labels: feat

#5 [2024/07/25] Fix/auth-front 프론트 : 회원가입 시 유효성 검사내용 출력
  src/main/resources/static/css/login.css
  src/main/resources/static/js/login.js
  src/main/resources/templates/login.html
Labels: fix

#8 [2024/07/25] fix/auth-front 회원가입 오류 수정
  src/main/resources/static/css/login.css
  src/main/resources/static/js/login.js
Labels: bug, fix

#10 [2024/07/26] bug/auth 로그아웃 세션 없음 문제 해결
  src/main/java/com/sparta/studytrek/domain/auth/entity/match/UserStatus.java
Labels: bug

#17 [2024/07/26]Feat/study like 스터디 좋아요 기능
  src/main/java/com/sparta/studytrek/domain/like/entity/StudyLike.java
  src/main/java/com/sparta/studytrek/domain/like/repository/StudyLikeRepository.java
Labels: feat

#19 [2024/07/26]bug/sidebar url 에 /api 추가
  src/main/resources/static/css/styles.css
  src/main/resources/static/js/login.js
  src/main/resources/static/js/scripts.js
  src/main/resources/templates/fragments/sidebar.html
  src/main/resources/templates/fragments/topbar.html
  src/main/resources/templates/home.html
Labels: bug

#24 [2024/07/28] feat/question-front 프론트 : 질문페이지 프론트 구현
  src/main/java/com/sparta/studytrek/web/ViewController.java
  src/main/resources/static/css/profile.css
  src/main/resources/static/css/question.css
  src/main/resources/static/css/styles.css
  src/main/resources/static/js/question.js
  src/main/resources/static/js/scripts.js
  src/main/resources/templates/fragments/sidebar.html
  src/main/resources/templates/fragments/topbar.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/question.html
Labels: feat, fix

#23 [2024/07/28] feat/review-front 프론트 : 리뷰 화면 스타일 통일
  src/main/resources/static/css/review/reviewDetail.css
  src/main/resources/static/css/review/reviewMain.css
  src/main/resources/templates/review/reviewDetail.html
  src/main/resources/templates/review/reviewMain.html
Labels: feat, fix

#22 [2024/07/28] feat/recruitment-front 프론트 : 부트캠프 모집글 페이지 구현
  src/main/java/com/sparta/studytrek/web/ViewController.java
  src/main/resources/static/css/recruitment/recruitmentAdd.css
  src/main/resources/static/css/recruitment/recruitmentDetail.css
  src/main/resources/static/css/recruitment/recruitmentMain.css
  src/main/resources/static/js/recruitment/recruitmentAdd.js
  src/main/resources/static/js/recruitment/recruitmentDetail.js
  src/main/resources/static/js/recruitment/recruitmentMain.js
  src/main/resources/templates/fragments/sidebar.html
  src/main/resources/templates/recruitment/recruitmentAdd.html
  src/main/resources/templates/recruitment/recruitmentDetail.html
  src/main/resources/templates/recruitment/recruitmentMain.html
Labels: feat, fix

#27 [2024/07/29] feat/Admin페이지 프론트 구현
  src/main/java/com/sparta/studytrek/web/ViewController.java
  src/main/resources/static/css/admin.css
  src/main/resources/static/css/question.css
  src/main/resources/static/js/admin.js
  src/main/resources/static/js/scripts.js
  src/main/resources/templates/admin.html
  src/main/resources/templates/fragments/sidebar.html
  src/main/resources/templates/fragments/topbar.html
  src/main/resources/templates/question.html
Labels: bug, feat, fix

#28 [2024/07/29] fix/스터디 & 랭크 페이지 구현 & 디자인 피드백 적용
  src/main/java/com/sparta/studytrek/web/ViewController.java
  src/main/resources/static/css/rank/Rank.css
  src/main/resources/static/css/ranktopsearch.css
  src/main/resources/static/css/study/StudyDetail.css
  src/main/resources/static/css/study/StudyMain.css
  src/main/resources/static/css/study/StudyModify.css
  src/main/resources/static/css/study/StudyWrite.css
  src/main/resources/static/css/studyMaintopsearch.css
  src/main/resources/static/js/rank/Rank.js
  src/main/resources/static/js/ranktopsearch.js
  src/main/resources/static/js/study/StudyDetail.js
  src/main/resources/static/js/study/StudyMain.js
  src/main/resources/static/js/study/StudyModify.js
  src/main/resources/static/js/study/StudyWrite.js
  src/main/resources/static/js/studyMaintopsearch.js
  src/main/resources/templates/fragments/ranktopsearch.html
  src/main/resources/templates/fragments/sidebar.html
  src/main/resources/templates/fragments/studyMaintopsearch.html
  src/main/resources/templates/rank/Rank.html
  src/main/resources/templates/study/StudyDetail.html
  src/main/resources/templates/study/StudyMain.html
  src/main/resources/templates/study/StudyModify.html
  src/main/resources/templates/study/StudyWrite.html
Labels: feat, fix

#34 [2024/07/29] [bugfix] feat/profile-admin-back 프론트 : url /api 제거
  src/main/java/com/sparta/studytrek/web/ViewController.java
  src/main/resources/static/js/login.js
  src/main/resources/static/js/recruitment/recruitmentAdd.js
  src/main/resources/static/js/scripts.js
  src/main/resources/templates/fragments/sidebar.html
  src/main/resources/templates/fragments/topbar.html
Labels: bug, fix

#38 [2024/07/29] Fix/entity 엔티티 연관관계 수정 및 클래스 이름 변경
  src/main/java/com/sparta/studytrek/domain/admin/service/AdminService.java
  src/main/java/com/sparta/studytrek/domain/auth/entity/User.java
  src/main/java/com/sparta/studytrek/domain/auth/entity/match/CampUser.java
  src/main/java/com/sparta/studytrek/domain/auth/service/RefreshTokenService.java
  src/main/java/com/sparta/studytrek/domain/auth/service/UserService.java
  src/main/java/com/sparta/studytrek/domain/camp/entity/Camp.java
  src/main/java/com/sparta/studytrek/domain/reply/entity/ReviewReply.java
  src/main/java/com/sparta/studytrek/domain/reply/entity/StudyReply.java
Labels: bug, fix

#39 [2024/07/30] feat/review-back 리뷰 CRUD 구현
  http/review.http
  src/main/java/com/sparta/studytrek/common/exception/ErrorCode.java
  src/main/java/com/sparta/studytrek/config/JPAConfig.java
  src/main/java/com/sparta/studytrek/domain/auth/repository/UserRepository.java
  src/main/java/com/sparta/studytrek/domain/auth/repository/UserRepositoryCustom.java
  src/main/java/com/sparta/studytrek/domain/auth/repository/UserRepositoryImpl.java
  src/main/java/com/sparta/studytrek/domain/auth/service/UserService.java
  src/main/java/com/sparta/studytrek/domain/camp/entity/Camp.java
  src/main/java/com/sparta/studytrek/domain/review/controller/ReviewController.java
  src/main/java/com/sparta/studytrek/domain/review/dto/ReviewRequestDto.java
  src/main/java/com/sparta/studytrek/domain/review/dto/ReviewResponseDto.java
  src/main/java/com/sparta/studytrek/domain/review/entity/Review.java
  src/main/java/com/sparta/studytrek/domain/review/repository/ReviewRepository.java
  src/main/java/com/sparta/studytrek/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/sparta/studytrek/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/sparta/studytrek/domain/review/service/ReviewService.java
Labels: feat

#43 [2024/07/30] Feat/study-back 스터디 CRUD 구현
  http/study.http
  src/main/java/com/sparta/studytrek/common/exception/ErrorCode.java
  src/main/java/com/sparta/studytrek/config/JPAConfig.java
  src/main/java/com/sparta/studytrek/domain/auth/entity/User.java
  src/main/java/com/sparta/studytrek/domain/like/entity/StudyLike.java
  src/main/java/com/sparta/studytrek/domain/reply/entity/StudyReply.java
  src/main/java/com/sparta/studytrek/domain/study/controller/StudyController.java
  src/main/java/com/sparta/studytrek/domain/study/dto/StudyRequestDto.java
  src/main/java/com/sparta/studytrek/domain/study/dto/StudyResponseDto.java
  src/main/java/com/sparta/studytrek/domain/study/entity/Study.java
  src/main/java/com/sparta/studytrek/domain/study/repository/StudyRepository.java
  src/main/java/com/sparta/studytrek/domain/study/repository/StudyRepositoryCustom.java
  src/main/java/com/sparta/studytrek/domain/study/repository/StudyRepositoryImpl.java
  src/main/java/com/sparta/studytrek/domain/study/service/StudyService.java
Labels: feat

#45 [2024/07/30] feat/review-comment 리뷰 댓글과 대댓글 CRUD 구현
  http/reveiwReply.http
  http/reviewComment.http
  src/main/java/com/sparta/studytrek/common/exception/ErrorCode.java
  src/main/java/com/sparta/studytrek/domain/comment/controller/ReviewCommentController.java
  src/main/java/com/sparta/studytrek/domain/comment/dto/CommentRequestDto.java
  src/main/java/com/sparta/studytrek/domain/comment/dto/CommentResponseDto.java
  src/main/java/com/sparta/studytrek/domain/comment/entity/ReviewComment.java
  src/main/java/com/sparta/studytrek/domain/comment/repository/ReviewCommentRepository.java
  src/main/java/com/sparta/studytrek/domain/comment/service/ReviewCommentService.java
  src/main/java/com/sparta/studytrek/domain/reply/controller/ReviewReplyController.java
  src/main/java/com/sparta/studytrek/domain/reply/dto/ReplyRequestDto.java
  src/main/java/com/sparta/studytrek/domain/reply/dto/ReplyResponseDto.java
  src/main/java/com/sparta/studytrek/domain/reply/entity/ReviewReply.java
  src/main/java/com/sparta/studytrek/domain/reply/repository/ReviewReplyRepository.java
  src/main/java/com/sparta/studytrek/domain/reply/service/ReviewReplyService.java
Labels: feat

#46 [2024/07/30] feat/recruitment-back 부트캠트 모집글 CRUD 구현
  http/recruitment.http
  src/main/java/com/sparta/studytrek/common/exception/ErrorCode.java
  src/main/java/com/sparta/studytrek/domain/recruitment/controller/RecruitmentController.java
  src/main/java/com/sparta/studytrek/domain/recruitment/dto/RecruitmentRequestDto.java
  src/main/java/com/sparta/studytrek/domain/recruitment/dto/RecruitmentResponseDto.java
  src/main/java/com/sparta/studytrek/domain/recruitment/entity/Recruitment.java
  src/main/java/com/sparta/studytrek/domain/recruitment/repository/RecruitmentRepository.java
  src/main/java/com/sparta/studytrek/domain/recruitment/service/RecruitmentService.java
Labels: feat

#53 [2024/07/31]Feat/like 좋아요, 좋아요 취소 구현
  http/auth.http
  http/campLike.http
  http/reviewLike.http
  http/studyLike.http
  src/main/java/com/sparta/studytrek/common/exception/ErrorCode.java
  src/main/java/com/sparta/studytrek/domain/like/controller/RecruitmentLikeController.java
  src/main/java/com/sparta/studytrek/domain/like/controller/ReviewLikeController.java
  src/main/java/com/sparta/studytrek/domain/like/controller/StudyLikeController.java
  src/main/java/com/sparta/studytrek/domain/like/entity/RecruitmentLike.java
  src/main/java/com/sparta/studytrek/domain/like/entity/ReviewLike.java
  src/main/java/com/sparta/studytrek/domain/like/entity/StudyLike.java
  src/main/java/com/sparta/studytrek/domain/like/repository/RecruitLikeRepository.java
  src/main/java/com/sparta/studytrek/domain/like/repository/RecruitmentLikeRepository.java
  src/main/java/com/sparta/studytrek/domain/like/repository/ReviewLikeRepository.java
  src/main/java/com/sparta/studytrek/domain/like/repository/StudyLikeRepository.java
  src/main/java/com/sparta/studytrek/domain/like/service/RecruitmentLikeService.java
  src/main/java/com/sparta/studytrek/domain/like/service/ReviewLikeService.java
  src/main/java/com/sparta/studytrek/domain/like/service/StudyLikeService.java
Labels: feat

#50 [2024/07/31] feat/study-comment 스터디 댓글과 대댓글 CRUD 구현
  http/studyComment.http
  http/studyReply.http
  src/main/java/com/sparta/studytrek/common/exception/ErrorCode.java
  src/main/java/com/sparta/studytrek/domain/comment/controller/StudyCommentController.java
  src/main/java/com/sparta/studytrek/domain/comment/dto/StudyCommentRequestDto.java
  src/main/java/com/sparta/studytrek/domain/comment/dto/StudyCommentResponseDto.java
  src/main/java/com/sparta/studytrek/domain/comment/entity/StudyComment.java
  src/main/java/com/sparta/studytrek/domain/comment/repository/StudyCommentRepository.java
  src/main/java/com/sparta/studytrek/domain/comment/service/StudyCommentService.java
  src/main/java/com/sparta/studytrek/domain/reply/controller/StudyReplyController.java
  src/main/java/com/sparta/studytrek/domain/reply/dto/StudyReplyRequestDto.java
  src/main/java/com/sparta/studytrek/domain/reply/dto/StudyReplyResponseDto.java
  src/main/java/com/sparta/studytrek/domain/reply/entity/StudyReply.java
  src/main/java/com/sparta/studytrek/domain/reply/repository/StudyReplyRepository.java
  src/main/java/com/sparta/studytrek/domain/reply/service/StudyReplyService.java
  src/main/java/com/sparta/studytrek/domain/study/controller/StudyController.java
Labels: feat
