Repository StUdY-TrEk/Boot-Camping, pull requests merged in 2024-08, with the labels that each got.

#54 [2024/07/31]Feat/question 질문 CRUD 구현
  http/question.http
  src/main/java/com/sparta/studytrek/common/exception/ErrorCode.java
  src/main/java/com/sparta/studytrek/domain/question/controller/QuestionController.java
  src/main/java/com/sparta/studytrek/domain/question/dto/QuestionRequestDto.java
  src/main/java/com/sparta/studytrek/domain/question/dto/QuestionResponseDto.java
  src/main/java/com/sparta/studytrek/domain/question/entity/Question.java
  src/main/java/com/sparta/studytrek/domain/question/repository/QuestionRepository.java
  src/main/java/com/sparta/studytrek/domain/question/repository/QuestionRepositoryCustom.java
  src/main/java/com/sparta/studytrek/domain/question/repository/QuestionRepositoryImpl.java
  src/main/java/com/sparta/studytrek/domain/question/service/QuestionService.java
Labels: feat

#55 [2024/07/31]Feat/anwser 답변 CRUD 구현
  http/answer.http
  http/auth.http
  src/main/java/com/sparta/studytrek/common/exception/ErrorCode.java
  src/main/java/com/sparta/studytrek/domain/answer/controller/AnswerController.java
  src/main/java/com/sparta/studytrek/domain/answer/dto/AnswerRequestDto.java
  src/main/java/com/sparta/studytrek/domain/answer/dto/AnswerResponseDto.java
  src/main/java/com/sparta/studytrek/domain/answer/entity/Answer.java
  src/main/java/com/sparta/studytrek/domain/answer/repository/AnswerRepository.java
  src/main/java/com/sparta/studytrek/domain/answer/service/AnswerService.java
  src/main/java/com/sparta/studytrek/domain/question/service/QuestionService.java
Labels: feat

#56 [2024/07/31]Feat/answer comment 답변에 대한 댓글 CRUD 구현
  http/answerComment.http
  src/main/java/com/sparta/studytrek/common/exception/ErrorCode.java
  src/main/java/com/sparta/studytrek/domain/comment/controller/AnswerCommentController.java
  src/main/java/com/sparta/studytrek/domain/comment/dto/AnswerCommentRequestDto.java
  src/main/java/com/sparta/studytrek/domain/comment/dto/AnswerCommentResponseDto.java
  src/main/java/com/sparta/studytrek/domain/comment/entity/AnswerComment.java
  src/main/java/com/sparta/studytrek/domain/comment/repository/AnswerCommentRepository.java
  src/main/java/com/sparta/studytrek/domain/comment/service/AnswerCommentService.java
Labels: feat

#57 [2024/08/01] feat/recruitment-front 부트캠프 모집글 프론트 연동
  http/recruitment.http
  src/main/java/com/sparta/studytrek/domain/recruitment/dto/RecruitmentRequestDto.java
  src/main/java/com/sparta/studytrek/domain/recruitment/dto/RecruitmentResponseDto.java
  src/main/java/com/sparta/studytrek/domain/recruitment/entity/Recruitment.java
  src/main/java/com/sparta/studytrek/web/ViewController.java
  src/main/resources/static/css/recruitment/recruitmentMain.css
  src/main/resources/static/js/recruitment/recruitmentAdd.js
  src/main/resources/static/js/recruitment/recruitmentDetail.js
  src/main/resources/static/js/recruitment/recruitmentMain.js
  src/main/resources/static/js/review/reviewAdd.js
  src/main/resources/templates/recruitment/recruitmentAdd.html
  src/main/resources/templates/recruitment/recruitmentDetail.html
  src/main/resources/templates/recruitment/recruitmentMain.html
Labels: feat

#59 [2024/08/01] feat/calendar 모집기간, 캠프 참여기간 API 조회 추가 및 캘린더 연동
  http/recruitment.http
  src/main/java/com/sparta/studytrek/domain/recruitment/controller/PeriodController.java
  src/main/java/com/sparta/studytrek/domain/recruitment/dto/ParticipatePeriodResponseDto.java
  src/main/java/com/sparta/studytrek/domain/recruitment/dto/RecruitPeriodResponseDto.java
  src/main/java/com/sparta/studytrek/domain/recruitment/repository/RecruitmentRepository.java
  src/main/java/com/sparta/studytrek/domain/recruitment/repository/RecruitmentRepositoryCustom.java
  src/main/java/com/sparta/studytrek/domain/recruitment/repository/RecruitmentRepositoryImpl.java
  src/main/java/com/sparta/studytrek/domain/recruitment/service/PeriodService.java
  src/main/java/com/sparta/studytrek/web/ViewController.java
  src/main/resources/static/css/recruitment/recruitmentMain.css
  src/main/resources/static/js/calendar/dist/index.global.js
  src/main/resources/static/js/calendar/dist/index.global.min.js
  src/main/resources/static/js/calendar/multimonth/index.global.js
  src/main/resources/static/js/calendar/multimonth/index.global.min.js
  src/main/resources/static/js/recruitment/recruitmentMain.js
  src/main/resources/templates/calendar/multimonth-view.html
  src/main/resources/templates/recruitment/recruitmentMain.html
Labels: feat

#64 [2024/08/02] Feat/profile-admin-back 관리자 CRUD 백엔드 구현
  build.gradle
  http/admin.http
  http/auth.http
  http/profile.http
  src/main/java/com/sparta/studytrek/common/exception/ErrorCode.java
  src/main/java/com/sparta/studytrek/config/SecurityConfig.java
  src/main/java/com/sparta/studytrek/domain/admin/controller/AdminController.java
  src/main/java/com/sparta/studytrek/domain/admin/dto/AdminRequestDto.java
  src/main/java/com/sparta/studytrek/domain/admin/dto/AdminResponseDto.java
  src/main/java/com/sparta/studytrek/domain/admin/entity/Admin.java
  src/main/java/com/sparta/studytrek/domain/admin/mapper/AdminMapper.java
  src/main/java/com/sparta/studytrek/domain/admin/repository/AdminRepository.java
  src/main/java/com/sparta/studytrek/domain/admin/service/AdminService.java
  src/main/java/com/sparta/studytrek/domain/admin/service/AdminServiceImpl.java
  src/main/java/com/sparta/studytrek/domain/auth/entity/UserRoleEnum.java
  src/main/java/com/sparta/studytrek/domain/auth/service/UserService.java
  src/main/java/com/sparta/studytrek/domain/camp/dto/CampRequestDto.java
  src/main/java/com/sparta/studytrek/domain/camp/dto/CampResponseDto.java
  src/main/java/com/sparta/studytrek/domain/camp/service/CampService.java
  src/main/java/com/sparta/studytrek/domain/profile/controller/ProfileController.java
  src/main/java/com/sparta/studytrek/domain/profile/dto/ProfileResponseDto.java
  src/main/java/com/sparta/studytrek/domain/profile/entity/Profile.java
  src/main/java/com/sparta/studytrek/domain/profile/entity/ProfileStatus.java
  src/main/java/com/sparta/studytrek/domain/profile/repository/ProfileRepository.java
  src/main/java/com/sparta/studytrek/domain/profile/service/ProfileService.java
  src/main/java/com/sparta/studytrek/domain/profile/service/ProfileServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/static/css/admin.css
  src/main/resources/static/css/profile.css
  src/main/resources/static/js/profile.js
  src/main/resources/templates/admin.html
Labels: feat, fix

#65 [2024/08/02] Feat/study 스터디 (+ 댓글, 대댓글) CRUD 프론트 연동
  http/rank.http
  src/main/java/com/sparta/studytrek/domain/camp/dto/CampResponseDto.java
  src/main/java/com/sparta/studytrek/domain/camp/entity/Camp.java
  src/main/java/com/sparta/studytrek/domain/rank/controler/RankController.java
  src/main/java/com/sparta/studytrek/domain/rank/dto/FilterRequest.java
  src/main/java/com/sparta/studytrek/domain/rank/dto/RankResponseDto.java
  src/main/java/com/sparta/studytrek/domain/rank/entity/Rank.java
  src/main/java/com/sparta/studytrek/domain/rank/repository/RankRepository.java
  src/main/java/com/sparta/studytrek/domain/rank/repository/RankRepositoryCustom.java
  src/main/java/com/sparta/studytrek/domain/rank/repository/RankRepositoryCustomImpl.java
  src/main/java/com/sparta/studytrek/domain/rank/service/RankService.java
  src/main/java/com/sparta/studytrek/web/ViewController.java
  src/main/resources/static/css/rank/Rank.css
  src/main/resources/static/css/study/StudyDetail.css
  src/main/resources/static/css/study/StudyMain.css
  src/main/resources/static/css/study/StudyModify.css
  src/main/resources/static/js/rank/Rank.js
  src/main/resources/static/js/ranktopsearch.js
  src/main/resources/static/js/study/StudyDetail.js
  src/main/resources/static/js/study/StudyMain.js
  src/main/resources/static/js/study/StudyModify.js
  src/main/resources/static/js/study/StudyWrite.js
  src/main/resources/static/js/studyMaintopsearch.js
  src/main/resources/templates/fragments/ranktopsearch.html
  src/main/resources/templates/fragments/studyMaintopsearch.html
  src/main/resources/templates/rank/Rank.html
  src/main/resources/templates/study/StudyDetail.html
  src/main/resources/templates/study/StudyMain.html
  src/main/resources/templates/study/StudyModify.html
  src/main/resources/templates/study/StudyWrite.html
Labels: feat, fix

#62 [2024/08/01] fix/auth 회원가입/로그인 유저 유형 구별 수정
  http/auth.http
  src/main/java/com/sparta/studytrek/common/exception/ErrorCode.java
  src/main/java/com/sparta/studytrek/common/exception/ExceptionResponse.java
  src/main/java/com/sparta/studytrek/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/studytrek/domain/auth/controller/UserController.java
  src/main/java/com/sparta/studytrek/domain/auth/dto/LoginRequestDto.java
  src/main/java/com/sparta/studytrek/domain/auth/dto/SignUpRequestDto.java
  src/main/java/com/sparta/studytrek/domain/auth/dto/SignUpResponseDto.java
  src/main/java/com/sparta/studytrek/domain/auth/entity/RefreshToken.java
  src/main/java/com/sparta/studytrek/domain/auth/entity/Role.java
  src/main/java/com/sparta/studytrek/domain/auth/entity/Status.java
  src/main/java/com/sparta/studytrek/domain/auth/entity/User.java
  src/main/java/com/sparta/studytrek/domain/auth/entity/match/UserStatus.java
  src/main/java/com/sparta/studytrek/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/com/sparta/studytrek/domain/auth/repository/RoleRepository.java
  src/main/java/com/sparta/studytrek/domain/auth/repository/StatusRepository.java
  src/main/java/com/sparta/studytrek/domain/auth/repository/UserRepositoryCustom.java
  src/main/java/com/sparta/studytrek/domain/auth/repository/UserStatusRepository.java
  src/main/java/com/sparta/studytrek/domain/auth/service/UserService.java
  src/main/java/com/sparta/studytrek/domain/auth/service/UserStatusService.java
  src/main/java/com/sparta/studytrek/jwt/JwtAuthorizationFilter.java
  src/main/java/com/sparta/studytrek/jwt/JwtUtil.java
  src/main/java/com/sparta/studytrek/security/UserDetailsServiceImpl.java
  src/main/resources/static/css/login.css
  src/main/resources/static/js/login.js
  src/main/resources/templates/login.html
Labels: bug, fix

#69 [2024/08/02] fefactor/hard-coding 하드코딩 & 개행 수정
  src/main/java/com/sparta/studytrek/common/ResponseText.java
  src/main/java/com/sparta/studytrek/domain/admin/controller/AdminController.java
  src/main/java/com/sparta/studytrek/domain/answer/controller/AnswerController.java
  src/main/java/com/sparta/studytrek/domain/auth/controller/UserController.java
  src/main/java/com/sparta/studytrek/domain/comment/controller/AnswerCommentController.java
  src/main/java/com/sparta/studytrek/domain/comment/controller/ReviewCommentController.java
  src/main/java/com/sparta/studytrek/domain/comment/controller/StudyCommentController.java
  src/main/java/com/sparta/studytrek/domain/like/controller/RecruitmentLikeController.java
  src/main/java/com/sparta/studytrek/domain/like/controller/ReviewLikeController.java
  src/main/java/com/sparta/studytrek/domain/like/controller/StudyLikeController.java
  src/main/java/com/sparta/studytrek/domain/profile/controller/ProfileController.java
  src/main/java/com/sparta/studytrek/domain/question/controller/QuestionController.java
  src/main/java/com/sparta/studytrek/domain/recruitment/controller/PeriodController.java
  src/main/java/com/sparta/studytrek/domain/recruitment/controller/RecruitmentController.java
  src/main/java/com/sparta/studytrek/domain/reply/controller/ReviewReplyController.java
  src/main/java/com/sparta/studytrek/domain/reply/controller/StudyReplyController.java
  src/main/java/com/sparta/studytrek/domain/review/controller/ReviewController.java
  src/main/java/com/sparta/studytrek/domain/study/controller/StudyController.java
  src/main/resources/static/css/login.css
  src/main/resources/static/css/styles.css
  src/main/resources/static/images/logo.png
  src/main/resources/static/js/login.js
  src/main/resources/static/js/scripts.js
  src/main/resources/templates/fragments/topbar.html
  src/main/resources/templates/login.html
Labels: feat, refactor

#71 [2024/08/03] fix/calendar 캘린더 메인 페이지로 이동
  src/main/java/com/sparta/studytrek/web/ViewController.java
  src/main/resources/static/css/recruitment/recruitmentMain.css
  src/main/resources/static/js/recruitment/recruitmentMain.js
  src/main/resources/templates/calendar/multimonth-view.html
  src/main/resources/templates/home.html
  src/main/resources/templates/recruitment/recruitmentMain.html
Labels: fix

#72 [2024/08/05] Feat/profile-admin-back 관리자페이지 프론트 연동
  http/admin.http
  http/profile.http
  src/main/java/com/sparta/studytrek/common/ResponseText.java
  src/main/java/com/sparta/studytrek/domain/admin/controller/AdminController.java
  src/main/java/com/sparta/studytrek/domain/profile/dto/ProfileResponseDto.java
  src/main/java/com/sparta/studytrek/domain/profile/entity/Profile.java
  src/main/java/com/sparta/studytrek/domain/profile/repository/ProfileRepository.java
  src/main/java/com/sparta/studytrek/domain/profile/service/ProfileService.java
  src/main/java/com/sparta/studytrek/domain/profile/service/ProfileServiceImpl.java
  src/main/resources/static/js/admin.js
Labels: feat

#74 [2024/08/06]Feat/front all question 질문, 답변, 댓글 프론트 연동
  http/answerComment.http
  src/main/java/com/sparta/studytrek/domain/comment/controller/AnswerCommentController.java
  src/main/java/com/sparta/studytrek/domain/comment/dto/AnswerCommentResponseDto.java
  src/main/java/com/sparta/studytrek/domain/comment/service/AnswerCommentService.java
  src/main/resources/static/css/question.css
  src/main/resources/static/js/question.js
  src/main/resources/templates/question.html
Labels: feat

#76 [2024/08/07]Fix/repository service에 있는 예외 처리 repository로 옮김
  src/main/java/com/sparta/studytrek/domain/answer/repository/AnswerRepository.java
  src/main/java/com/sparta/studytrek/domain/answer/service/AnswerService.java
  src/main/java/com/sparta/studytrek/domain/comment/repository/AnswerCommentRepository.java
  src/main/java/com/sparta/studytrek/domain/comment/repository/ReviewCommentRepository.java
  src/main/java/com/sparta/studytrek/domain/comment/repository/StudyCommentRepository.java
  src/main/java/com/sparta/studytrek/domain/comment/service/AnswerCommentService.java
  src/main/java/com/sparta/studytrek/domain/comment/service/ReviewCommentService.java
  src/main/java/com/sparta/studytrek/domain/comment/service/StudyCommentService.java
  src/main/java/com/sparta/studytrek/domain/like/service/RecruitmentLikeService.java
  src/main/java/com/sparta/studytrek/domain/like/service/ReviewLikeService.java
  src/main/java/com/sparta/studytrek/domain/like/service/StudyLikeService.java
  src/main/java/com/sparta/studytrek/domain/question/repository/QuestionRepository.java
  src/main/java/com/sparta/studytrek/domain/question/service/QuestionService.java
  src/main/java/com/sparta/studytrek/domain/recruitment/repository/RecruitmentRepository.java
  src/main/java/com/sparta/studytrek/domain/recruitment/service/RecruitmentService.java
  src/main/java/com/sparta/studytrek/domain/reply/repository/ReviewReplyRepository.java
  src/main/java/com/sparta/studytrek/domain/reply/repository/StudyReplyRepository.java
  src/main/java/com/sparta/studytrek/domain/reply/service/ReviewReplyService.java
  src/main/java/com/sparta/studytrek/domain/reply/service/StudyReplyService.java
  src/main/java/com/sparta/studytrek/domain/review/repository/ReviewRepository.java
  src/main/java/com/sparta/studytrek/domain/review/service/ReviewService.java
  src/main/java/com/sparta/studytrek/domain/study/repository/StudyRepository.java
  src/main/java/com/sparta/studytrek/domain/study/service/StudyService.java
Labels: refactor

#81 [2024/08/08] Feat/aop 권한 체크 AOP 추가
  http/auth.http
  src/main/java/com/sparta/studytrek/aop/AdminRoleCheck.java
  src/main/java/com/sparta/studytrek/aop/RecruitmentRoleCheck.java
  src/main/java/com/sparta/studytrek/aop/ReviewRoleCheck.java
  src/main/java/com/sparta/studytrek/aop/StudyRoleCheck.java
  src/main/java/com/sparta/studytrek/aop/UserRoleAop.java
  src/main/java/com/sparta/studytrek/common/exception/CustomException.java
  src/main/java/com/sparta/studytrek/common/exception/ErrorCode.java
  src/main/java/com/sparta/studytrek/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/studytrek/domain/admin/controller/AdminController.java
  src/main/java/com/sparta/studytrek/domain/auth/entity/Role.java
  src/main/java/com/sparta/studytrek/domain/recruitment/controller/RecruitmentController.java
  src/main/java/com/sparta/studytrek/domain/review/controller/ReviewController.java
  src/main/java/com/sparta/studytrek/domain/study/controller/StudyController.java
  src/main/java/com/sparta/studytrek/jwt/JwtUtil.java
  src/main/resources/static/js/recruitment/recruitmentAdd.js
  src/main/resources/static/js/review/reviewAdd.js
  src/main/resources/static/js/study/StudyWrite.js
Labels: feat

#87 [2024/08/14] Feat/GitHub action CI/CD 설정
  .github/workflows/github-actions.yml
  Dockerfile
  src/main/java/com/sparta/studytrek/common/exception/ExceptionResponse.java
  src/main/java/com/sparta/studytrek/common/exception/GlobalExceptionHandler.java
  src/main/resources/application.properties
Labels: feat

#91 [2024/08/14] Feat/query-optimization url 수정
  src/main/resources/static/js/auth.js
Labels: bug

#80 [2024/08/08] Fix/rank-back 순위 기능 구현 & 프론트 연동
  build.gradle
  http/campLike.http
  src/main/java/com/sparta/studytrek/StudyTrekApplication.java
  src/main/java/com/sparta/studytrek/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/studytrek/domain/camp/entity/Camp.java
  src/main/java/com/sparta/studytrek/domain/camp/scheduler/CampRankingScheduler.java
  src/main/java/com/sparta/studytrek/domain/camp/service/CampService.java
  src/main/java/com/sparta/studytrek/domain/like/controller/CampLikeController.java
  src/main/java/com/sparta/studytrek/domain/like/entity/CampLike.java
  src/main/java/com/sparta/studytrek/domain/like/repository/CampLikeRepository.java
  src/main/java/com/sparta/studytrek/domain/rank/dto/RankResponseDto.java
  src/main/java/com/sparta/studytrek/domain/rank/entity/Rank.java
  src/main/java/com/sparta/studytrek/domain/rank/repository/RankRepository.java
  src/main/java/com/sparta/studytrek/domain/rank/service/RankService.java
  src/main/resources/application.properties
  src/main/resources/static/css/question.css
  src/main/resources/static/css/rank/Rank.css
  src/main/resources/static/css/recruitment/recruitmentMain.css
  src/main/resources/static/css/review/reviewMain.css
  src/main/resources/static/css/study/StudyDetail.css
  src/main/resources/static/css/study/StudyMain.css
  src/main/resources/static/js/rank/Rank.js
  src/main/resources/static/js/study/StudyDetail.js
  src/main/resources/static/js/study/StudyWrite.js
  src/main/resources/templates/question.html
  src/main/resources/templates/recruitment/recruitmentMain.html
  src/main/resources/templates/review/reviewMain.html
  src/main/resources/templates/study/StudyMain.html
Labels: feat, fix

#93 [2024/08/14] Feat/query-optimization url 수정3
  src/main/java/com/sparta/studytrek/config/SecurityConfig.java
  src/main/java/com/sparta/studytrek/config/WebSocketconfig.java
  src/main/resources/static/js/auth.js
Labels: bug

#95 [2024/08/17] bug/websocket App Runner WebSocket 지원X 문제 (1차)
  src/main/resources/static/js/auth.js
Labels: bug, fix

#96 [2024/08/17] bug/websocket App Runner WebSocket 지원X 문제 (2차)
  src/main/resources/static/js/auth.js
Labels: bug, fix

#97 [2024/08/17] bug/websocket App Runner WebSocket 지원X 문제 WebSocket을 SSE 로 변경
  src/main/java/com/sparta/studytrek/config/SecurityConfig.java
  src/main/java/com/sparta/studytrek/config/WebSocketconfig.java
  src/main/java/com/sparta/studytrek/domain/answer/service/AnswerService.java
  src/main/java/com/sparta/studytrek/domain/chat/controller/ChatController.java
  src/main/java/com/sparta/studytrek/domain/chat/service/ChatService.java
  src/main/java/com/sparta/studytrek/domain/chat/service/ChatServiceImpl.java
  src/main/java/com/sparta/studytrek/domain/comment/service/AnswerCommentService.java
  src/main/java/com/sparta/studytrek/domain/comment/service/ReviewCommentService.java
  src/main/java/com/sparta/studytrek/domain/comment/service/StudyCommentService.java
  src/main/java/com/sparta/studytrek/domain/profile/service/ProfileServiceImpl.java
  src/main/java/com/sparta/studytrek/domain/reply/service/ReviewReplyService.java
  src/main/java/com/sparta/studytrek/domain/reply/service/StudyReplyService.java
  src/main/java/com/sparta/studytrek/websocket/controller/NotificationController.java
  src/main/java/com/sparta/studytrek/websocket/handler/ChatHandler.java
  src/main/java/com/sparta/studytrek/websocket/handler/NotificationHandler.java
  src/main/java/com/sparta/studytrek/websocket/service/NotificationService.java
  src/main/resources/application.properties
  src/main/resources/static/js/alarm.js
  src/main/resources/static/js/auth.js
  src/main/resources/static/js/chat.js
Labels: bug, fix

#98 [2024/08/18] bug/websocket App Runner WebSocket 지원X 문제 SSE 중복문제 해결
  src/main/resources/application.properties
  src/main/resources/static/js/auth.js
  src/main/resources/templates/rank/Rank.html
Labels: bug, fix

#100 [2024/08/19] Feat/camp-test 캠프 테스트 코드 추가
  src/main/java/com/sparta/studytrek/domain/camp/service/CampService.java
  src/main/resources/application.properties
  src/test/java/com/sparta/studytrek/domain/camp/service/CampServiceTest.java
Labels: test

#105 [2024/08/20] Feat/front admin 관리자 로그인/회원가입 페이지 추가 및 연동
  src/main/java/com/sparta/studytrek/web/ViewController.java
  src/main/resources/static/css/adminLogin.css
  src/main/resources/static/js/adminLogin.js
  src/main/resources/static/js/login.js
  src/main/resources/templates/admin.html
  src/main/resources/templates/adminLogin.html
Labels: feat

#102 [2024/08/19] Feat/notification-chat-test 알림목록조회, 메시지저장 테스트 코드
  src/test/java/com/sparta/studytrek/domain/chat/service/ChatServiceTest.java
  src/test/java/com/sparta/studytrek/notification/service/NotificationServiceTest.java
Labels: test

#106 [2024/08/20] Feat/query 커서페이징 최적화, 알림목록 오류 해결
  src/main/java/com/sparta/studytrek/domain/chat/controller/ChatController.java
  src/main/java/com/sparta/studytrek/domain/chat/dto/ChatMessageRequestDto.java
  src/main/java/com/sparta/studytrek/domain/chat/dto/ChatMessageResponseDto.java
  src/main/java/com/sparta/studytrek/domain/chat/repository/ChatRepository.java
  src/main/java/com/sparta/studytrek/domain/chat/repository/ChatRepositoryCustom.java
  src/main/java/com/sparta/studytrek/domain/chat/repository/ChatRepositoryCustomImpl.java
  src/main/java/com/sparta/studytrek/domain/chat/service/ChatService.java
  src/main/java/com/sparta/studytrek/domain/chat/service/ChatServiceImpl.java
  src/main/java/com/sparta/studytrek/notification/repository/NotificationRepository.java
  src/main/java/com/sparta/studytrek/notification/repository/NotificationRepositoryCustom.java
  src/main/java/com/sparta/studytrek/notification/repository/NotificationRepositoryCustomImpl.java
  src/main/java/com/sparta/studytrek/notification/service/NotificationService.java
  src/main/resources/static/js/auth.js
Labels: bug, feat, fix

#109 [2024/08/20] Feat/admin-front Admin 계정만 Admin 페이지버튼 사용 가능
  src/main/resources/application.properties
  src/main/resources/static/js/scripts.js
Labels: bug, feat, fix

#111 [2024/08/20] feat/summary 요약 API 프론트 연동
  src/main/resources/static/css/recruitment/recruitmentDetail.css
  src/main/resources/static/js/recruitment/recruitmentDetail.js
  src/main/resources/templates/recruitment/recruitmentDetail.html
Labels: feat

#113 [2024/08/20] bug/camp getAllRanks 메서드에 대한 로그 삽입
  src/main/java/com/sparta/studytrek/domain/rank/service/RankService.java
Labels: bug

#114 [2024/08/20] main < devlop 작업 내용 서버 업데이트
  .github/workflows/github-actions.yml
  src/main/java/com/sparta/studytrek/domain/rank/service/RankService.java
  src/main/resources/static/css/recruitment/recruitmentDetail.css
  src/main/resources/static/js/recruitment/recruitmentDetail.js
  src/main/resources/templates/recruitment/recruitmentDetail.html
Labels: feat

#118 [2024/08/20] Fix/review-front 작성자 대신 부트캠프 이름으로 변경
  src/main/resources/static/js/review/reviewMain.js
Labels: fix

#120 [2024/08/20] Bug/review 리뷰 등록 오류 수정 및 예외 메시지 출력
  src/main/java/com/sparta/studytrek/domain/auth/repository/CampUserRepository.java
  src/main/java/com/sparta/studytrek/domain/auth/repository/CampUserRepositoryCustom.java
  src/main/java/com/sparta/studytrek/domain/auth/repository/CampUserRepositoryImpl.java
  src/main/java/com/sparta/studytrek/domain/auth/repository/UserRepository.java
  src/main/java/com/sparta/studytrek/domain/auth/service/UserService.java
  src/main/java/com/sparta/studytrek/domain/camp/entity/Camp.java
  src/main/java/com/sparta/studytrek/domain/review/controller/ReviewController.java
  src/main/java/com/sparta/studytrek/domain/review/dto/ReviewRequestDto.java
  src/main/resources/static/js/review/reviewAdd.js
  src/main/resources/templates/review/reviewAdd.html
Labels: bug

#122 [2024/08/21] Bug/auth 사용자 인증 관련 유저 피드백 & 오류 수정
  src/main/java/com/sparta/studytrek/common/exception/ErrorCode.java
  src/main/java/com/sparta/studytrek/domain/auth/service/UserService.java
  src/main/resources/static/js/login.js
  src/main/resources/static/js/scripts.js
  src/main/resources/templates/fragments/sidebar.html
Labels: bug, fix

#116 [2024/08/20 Fix/admin front 이미지 폼 추가 & description 추가
  src/main/java/com/sparta/studytrek/domain/rank/dto/RankResponseDto.java
  src/main/java/com/sparta/studytrek/domain/rank/service/RankService.java
  src/main/resources/static/css/rank/Rank.css
  src/main/resources/static/js/rank/Rank.js
  src/main/resources/templates/admin.html
Labels: feat, fix

#125 [2024/08/21] main < devlop 작업 내용 업데이트
  src/main/java/com/sparta/studytrek/common/exception/ErrorCode.java
  src/main/java/com/sparta/studytrek/domain/auth/repository/CampUserRepository.java
  src/main/java/com/sparta/studytrek/domain/auth/repository/CampUserRepositoryCustom.java
  src/main/java/com/sparta/studytrek/domain/auth/repository/CampUserRepositoryImpl.java
  src/main/java/com/sparta/studytrek/domain/auth/repository/UserRepository.java
  src/main/java/com/sparta/studytrek/domain/auth/service/UserService.java
  src/main/java/com/sparta/studytrek/domain/camp/entity/Camp.java
  src/main/java/com/sparta/studytrek/domain/rank/dto/RankResponseDto.java
  src/main/java/com/sparta/studytrek/domain/rank/service/RankService.java
  src/main/java/com/sparta/studytrek/domain/review/controller/ReviewController.java
  src/main/java/com/sparta/studytrek/domain/review/dto/ReviewRequestDto.java
  src/main/resources/static/css/rank/Rank.css
  src/main/resources/static/js/login.js
  src/main/resources/static/js/rank/Rank.js
  src/main/resources/static/js/review/reviewAdd.js
  src/main/resources/static/js/review/reviewDetail.js
  src/main/resources/static/js/review/reviewMain.js
  src/main/resources/static/js/scripts.js
  src/main/resources/templates/admin.html
  src/main/resources/templates/fragments/sidebar.html
  src/main/resources/templates/review/reviewAdd.html
Labels: feat

#129 [2024/08/21] Fix/question 질문, 답변, 댓글 수정, 삭제 수정
  src/main/java/com/sparta/studytrek/common/exception/ErrorCode.java
  src/main/java/com/sparta/studytrek/domain/answer/service/AnswerService.java
  src/main/java/com/sparta/studytrek/domain/comment/service/AnswerCommentService.java
  src/main/java/com/sparta/studytrek/domain/question/service/QuestionService.java
Labels: fix
